ALTER TABLE meals ADD COLUMN meal_type TEXT NOT NULL DEFAULT 'snack';
ALTER TABLE meals ADD COLUMN total_protein_g REAL NOT NULL DEFAULT 0;
ALTER TABLE meals ADD COLUMN total_carbs_g REAL NOT NULL DEFAULT 0;
ALTER TABLE meals ADD COLUMN total_fat_g REAL NOT NULL DEFAULT 0;
